# Conker's Bad Fur Day (USA) — Master Symbol Table for N64Recomp
[[section]]
name = "init.us"
rom = 0x00001000
vram = 0x80001000
size = 0x00025000

functions = [
  { name = "entrypoint", vram = 0x80001000, size = 0x60 },
  { name = "bootproc", vram = 0x80001060, size = 0x171C },
  { name = "main_switch_handler", vram = 0x8000277C, size = 0x634 },
  { name = "_VirtualToPhysicalTask", vram = 0x80003220, size = 0x110 },
  { name = "viMgrMain", vram = 0x80003658, size = 0x198 },
  { name = "allocate_memory", vram = 0x80003C40, size = 0x1930 },
  { name = "_MakeMotorData", vram = 0x800057E0, size = 0x168 },
  { name = "__osCleanupThread", vram = 0x80007BF8, size = 0x408 },
  { name = "osGetTime", vram = 0x800230F0, size = 0x40 }
]
