# Conker's Bad Fur Day (USA) — N64Recomp Configuration
[input]
symbols_file_path = "conker.symbols.toml"
rom_file_path     = "baserom.us.z64"
output_func_path  = "recomp/src/generated"

entrypoint = 0x80001000
functions_per_output_file = 50
single_file_output   = false
use_absolute_symbols = true
recomp_include = "#include \"recomp.h\""

[patches]
stubs = [
  "bootproc",
  "allocate_memory"
]
ignored = []
